import praw

reddit = praw.Reddit(
    client_id="",                                         #Generated by Reddit - input client_id here
    client_secret="",                                     #Generated by Reddit - input client_secret here
    user_agent="",                                        #Can be any unique app name
    username="",                                          #Input reddit username here
    password=""                                           #Input password for reddit account here
)

subreddit = reddit.subreddit("stocks+investing")        #Add subreddits here - separate subreddits with "+" or input "all" for all subreddits
for submission in subreddit.stream.submissions():
    if "stock" in submission.title:                     #Change keyword here
        print('***************')
        print(submission.subreddit.display_name)
        print(submission.title)
        submission.upvote()                             #Can also downvote posts with .downvote()
